export type StackParams = {
  ItemScreen: any;
  MainHomeScreen: any;
  ShoppingBagScreen: any;
  CheckoutScreen: any;
  ChatDetailsScreen: any;
  OrderDetailsScreen: any;
  NotificationScreen: any;
  AllChatsScreen: any;
  SearchContactScreen: any;
  LogInScreen: any;
  ProfileScreen: any;
  RegisterScreen: any;
  AddLocationMapScreen: any;
  EditAddressScreen: any;
  ReportUserScreen: any;
  SellOrEditItemScreen: any;
  ChatScreen: any;
  LoadingScreen: any;
  BottomTabNav: any;
  CheckoutStack: any;
  MapScreen: any;
};
